### ISSUE TITLE
Not 100% compatible with SQLAlchemy 1.4

### ISSUE THREAD

**Issue by kadler** [IBM/sqlalchemy-ibmi#133]
Until now we've focused on building for SQLAlchemy 1.3, but since then 1.4 has come out. It seems that some things work, but other things do not work (see #131).

We need to run the SQLAlchemy 1.4 test suite and fix any issues found.

There's a 1.4 migration guide here: https://docs.sqlalchemy.org/en/14/changelog/migration_14.html

**Comment by blake-hamm** [comment]
This would be an excellent fix! I am unable to use dask and prefect with this package until addressed. Instead, I will need to load the data in a pandas dataframe and then convert it to a dask dataframe using extra memory.

**Comment by clemens-zauchner** [comment]
With pandas version 1.5.2, there is an error when trying to use `pd.DataFrame().to_sql()`:

> ImportError: Unable to find a usable engine; tried using: 'sqlalchemy'.
> A suitable version of sqlalchemy is required for sql I/O support.
> Trying to import the above resulted in these errors:
> - Pandas requires version '1.4.16' or newer of 'sqlalchemy' (version '1.3.24' currently installed).

it still works to read data from a db, but writing to it seems to be impossible.

**Comment by kadler** [comment]
Start of support with #148. I also have some changes to follow which gets their test suite to pass.

**Comment by kadler** [comment]
This should be working now with https://github.com/IBM/sqlalchemy-ibmi/releases/tag/0.9.3
