### ISSUE TITLE
is this required for ibm i and sqlalchemy

### ISSUE THREAD

**Issue by qvsdeveloper** [IBM/sqlalchemy-ibmi#135]
When I attempt to use ibm_db and ibm_db_sa to connect to IBM i DB2 I receive the error: SQL1598N 

is sqlalchemy-ibmi required to connect to ibm i v7r3 ?

**Comment by kadler** [comment]
Using ibm_db_sa _may_ work, however the upstream devs don't test or care much about IBM i. In addition, you will need a Db2 Connect Unlimited for System i license in order to use it.

Alternatively, you can use sqlalchemy-ibmi, which uses PyODBC with the free IBM i Access ODBC driver.

**Comment by qvsdeveloper** [comment]
update - it works well with the ibm i ! :)  As a python and pandas newbie, I appreaciate finding sqlalchemy-ibmi just worked to upload a pandas dataframe to_sql to an ibm i database file!
