### ISSUE TITLE
Can't connect to DB , with engine = sa.create_engine("ibmi://user:pass@host") result in missing system odbc error

### ISSUE THREAD

**Issue by openmax** [IBM/sqlalchemy-ibmi#136]
weird result for a malformed connection string on ubuntu 20.04.4 , python 3.8.10 

https://github.com/IBM/sqlalchemy-ibmi/blob/6a0a5038f1e1d6955af46ae6e61e8440a903fedd/sqlalchemy_ibmi/base.py#L864

fixed by remove last semicolon :
return [["Driver={%s}; UNICODESQL=1; TRUEAUTOCOMMIT=1; XDYNAMIC=0" % (

**Comment by 2ps** [comment]
I had this exact same issue; thank you openmax!

**Comment by 2ps** [comment]
@openmax  -- went ahead and made the update.  released as https://pypi.org/project/crazy-ibmi .  Assuming that @kadler  and @naveen-ram  have moved onto other projects.  Please let me know if you'd like to be added as a contributor to the new project.

**Comment by openmax** [comment]
@2ps thank you , no need to be added as contributor .

**Comment by kadler** [comment]
This seems to have been fixed with #139
