### ISSUE TITLE
Implement abstract methods identified by pylint

### ISSUE THREAD

**Issue by naveen-ram** [IBM/sqlalchemy-ibmi#19]
Classes:
- DB2Dialect
- DB2Compiler
- DB2ExecutionContext
- CoerceUnicode
- Requirements

**Comment by kadler** [comment]
It seems that the way SQLAlchemy is designed you are not supposed to implement methods that are not supported for your database adapter. By defining certain methods (even if they're stub "pass" functions), SQLAlchemy assumes that the behavior is implemented and will try to use it even though it's not, which causes many problems.

While pylint has good intentions for best practices, we are bound to the behavior and design of SQLAlchemy so we can't follow these suggestions.
