### ISSUE TITLE
Remove useless CoerceUnicode class

### ISSUE THREAD

**Issue by kadler** [IBM/sqlalchemy-ibmi#40]
The original class we imported from ibm_db_sa was this: https://github.com/IBM/sqlalchemy-ibmi/blob/a737630a61c6eae990ba5e5b4190c0177e9fd093/ibm_db_sa/ibm_db_sa/reflection.py#L28-L34

This is basically pointless. It seems that this was changed for Python 3 support here: https://github.com/IBM/sqlalchemy-ibmi/commit/657888b69656663b3dc0429336b86eb38f3bada2#diff-23f8c2093bac5bb5b04f8def0f590b6bL33 This sort of makes sense, as in Python 2, there was a difference between `str` and `unicode` types and `str.decode` would deocde the bytes in the `str` to a `unicode` object. In Python 3, there is just `str`, which is Unicode. I'm not sure why they didn't make it continue working with Python 2, though :man_shrugging:.

I think we can just replace all references to `sa_types.Unicode` instead.

**Comment by naveen-ram** [comment]
Will remove once the reflector is merged in master
