### ISSUE TITLE
Implement correct isolation levels for IBMi

### ISSUE THREAD

**Issue by naveen-ram** [IBM/sqlalchemy-ibmi#52]
The current pyodbc code only uses autocommit true or false for isolation levels when IBMi supports additional isolation levels

**Comment by kadler** [comment]
PyODBC supports 4 different isolation levels: https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management and IBM i supports all of these levels as well. We also have an IBM i-specific level (`*NONE`) that we can try to support as well, though I don't know whether PyODBC can support this.
