### ISSUE TITLE
Fix broken create_connect_args

### ISSUE THREAD

**Issue by naveen-ram** [IBM/sqlalchemy-ibmi#55]
When sqlalchemy connects now it doesn't work because it cannot connect to the IBM i system. In the previous code, if the host was provided and not a database, then the 'dsn' keyword would be used. In our updated code, we are providing a 'host' and a 'database' as None and as a result, when trying to connect the following message results:
Missing system name needed for connection.

**Comment by kadler** [comment]
Is it this error?

```
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'None' : file not found (0) (SQLDriverConnect)")
```

**Comment by kadler** [comment]
Never mind, that was the problem in testing-setup branch because `pyodbc_driver_name` was set to `None` instead of "IBM i Access ODBC Driver".
