### ISSUE TITLE
Unicode conversion doesn't work with Linux IBM i Access ODBC driver

### ISSUE THREAD

**Issue by naveen-ram** [IBM/sqlalchemy-ibmi#69]
When we pass the UNICODESQL=1 connection option, the result works when connecting using the driver on Windows but using the driver in Linux causes the tests that pass in windows to fail in Linux. Until this can be fixed, those test will be skipped.

**Comment by kadler** [comment]
I'm working on a driver fix for this.

**Comment by kadler** [comment]
This should be fixed in the latest couple service packs.
