### ISSUE TITLE
Excluding length when creating a String column does not work

### ISSUE THREAD

**Issue by naveen-ram** [IBM/sqlalchemy-ibmi#78]
Using the following mapping 

class User(Base):
        __tablename__ = 'users'
       name = Column(String)

will lead to a SQL0104 - Token ( was not valid. error from Db2. 
Possible course of action is to set a default varchar size when a string is passed without a size.

**Comment by kadler** [comment]
https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.String.__init__

> length – optional, a length for the column for use in DDL and CAST expressions. May be safely omitted if no CREATE TABLE will be issued. Certain databases may require a length for use in DDL, and **will raise an exception when the CREATE TABLE DDL is issued if a VARCHAR with no length is included.**

(emphasis mine)

Seems like it's working as designed?

**Comment by naveen-ram** [comment]
Then maybe we could include this as an enhancement to avoid the error for the user?

**Comment by kadler** [comment]
Maybe. I think we should focus on getting the base functionality done first.

**Comment by kadler** [comment]
Replaced by #125
