### ISSUE TITLE
Using func.count('*') doesn't work

### ISSUE THREAD

**Issue by naveen-ram** [IBM/sqlalchemy-ibmi#80]
Doing this causes an error because it puts a parameter marker in the SELECT clause of the sql query which is not supported on Db2 on IBM i.

**Comment by naveen-ram** [comment]
Using func.count() uses a literal_column version of the '*', bypassing the parameter marker issue that was caused. 

See code that does this here:
https://github.com/sqlalchemy/sqlalchemy/blob/447c0750e1f739c4db1d0d20de182c297dc86e36/lib/sqlalchemy/sql/functions.py#L855-L882

We can document to use func.count() in queries rather than func.count(*). The query will not accept strings as this will create a parameter marker again in the resulting sql query.

**Comment by kadler** [comment]
What if you want to count things other than all the rows?

**Comment by naveen-ram** [comment]
The follow describes how to use func.count() without the string input

`from sqlalchemy import func

# count User records, without
# using a subquery.
session.query(func.count(User.id))

# return count of user "id" grouped
# by "name"
session.query(func.count(User.id)).\
        group_by(User.name)

from sqlalchemy import distinct

# count distinct "name" values
session.query(func.count(distinct(User.name)))`

**Comment by kadler** [comment]
Does that actually work, though?

**Comment by naveen-ram** [comment]
yup that works, the following command:
`session.query(func.count(User.name), User.name).group_by(User.name).all()`
produces the following SQL:
```
SELECT count(users.name) AS count_1, users.name AS users_name 
FROM users GROUP BY users.name
```
The issue comes when you input a string into the func.count() method. Then it uses a parameter marker in the select statement.

**Comment by kadler** [comment]
I wonder if we could override that somehow. It looks like just by declaring the class, that registers it with func. I wonder what would happen if you re-declared it, would it override the one that SQLAlchemy defines?

Alternatively, is there something that we need to specify in our adapter that tells SQLAlchemy that we don't support parameter markers in the select clause?

**Comment by naveen-ram** [comment]
I don't think that we can specify that with SQLAlchemy. I will look into all the functions that might include using a parameter marker where it shouldn't be used and see if we can override the behavior in those cases.

**Comment by naveen-ram** [comment]
Looking at the code, it seems if the user is inputting a string, if they use literal_column imported from sqlalchemy.sql, the error goes away. 

For example:

`session.query(func.count("name")).select_from(User).scalar()`
`session.query(func.count("*")).select_from(User).scalar()`

will cause the parameter marker error, whereas

`session.query(func.count(literal_column("name"))).select_from(User).scalar()`
`session.query(func.count(literal_column("*"))).select_from(User).scalar()`

doesn't, and displays the right result. So maybe the best course is to suggest the user to input strings as literal_columns.

**Comment by naveen-ram** [comment]
Documented in read the docs, can this be closed?

**Comment by kadler** [comment]
We need to merge #85 first

**Comment by kadler** [comment]
#85 has been merged, closing
